version: "3.8"

services:
    webapp:
        build: .
        container_name: webapp
        restart: always
        ports:
            - "80:8080"
        volumes:
            - ./webapp:/app
        env_file: .env
